export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR";

export const FUTURE_WEATHER_REQUEST = "FUTURE_WEATHER_REQUEST";
export const FUTURE_WEATHER_SUCCESS = "FUTURE_WEATHER_SUCCESS";
export const FUTURE_WEATHER_ERROR = "FUTURE_WEATHER_ERROR";